version: '3.8'

services:

  # Databases
  master_db:
    image: postgres:latest
    container_name: master_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: app_db
      REPLICATION_USER: ${REPLICATION_USER}
      REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
    volumes:
      - conf:/etc/postgresql
      - master_db_data:/var/lib/postgresql/data
    command: postgres -c 'config_file=/etc/postgresql/master_postgres.conf'
    networks:
      - app_network

volumes:
  conf:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ${PWD}/conf
  master_db_data:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ${PWD}/docker_fs/master_db  
networks:
  app_network:
    driver: bridge
