version: '2'

# for other configuration please check out the documentation : https://hub.docker.com/r/bitnami/postgresql

x-postgres-environment:
  &postgres-environment
  POSTGRESQL_USERNAME:  ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRESQL_REPLICATION_USER: ${REPLICATION_USER:-replication_user}
  POSTGRESQL_REPLICATION_PASSWORD: ${REPLICATION_PASSWORD:-replication_password}
  POSTGRESQL_DATABASE: ${DB_NAME}


# common settings
x-postgres-common:
  &postgres-common
  image: bitnami/postgresql:latest
  restart: always
  environment:
    <<: *postgres-environment
  healthcheck:
    test: 'pg_isready -U ${POSTGRESQL_USERNAME:-postgres} --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5

services:
  master_db:
    container_name: master_db
    <<: *postgres-common
    # volumes:
    #   - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      <<: *postgres-environment
      POSTGRESQL_REPLICATION_MODE: master

  slave_db1:
    container_name: slave_db1
    <<: *postgres-common
    environment:
      <<: *postgres-environment
      POSTGRESQL_MASTER_HOST: master_db
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
      POSTGRESQL_REPLICATION_MODE: slave
    depends_on:
      - master_db

  slave_db2:
    container_name: slave_db2
    <<: *postgres-common
    environment:
      <<: *postgres-environment
      POSTGRESQL_MASTER_HOST: master_db
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
      POSTGRESQL_REPLICATION_MODE: slave
    depends_on:
      - master_db

volumes:
  postgresql_master_data:
    driver: local